### ISSUE TITLE
Apply changes before we get a response from the API server, to make the app more responsive.

### ISSUE THREAD

**Issue by karate** [karate/todo#5]
When the user adds a new task, add the task (marked as uncofirmed) before we get a response from the API. Mark task as confirmed on AJAX success. This way the app will be more responsive. This has to be implemented for all current API calls (delete task, and mark task as done).

**Comment by mpurgatori** [comment]
How is task to be marked?

**Comment by sabarnac** [comment]
#6 Added a change. If a change in the confirmation label is required, do say so 😄

**Comment by karate** [comment]
It's great @sabarnac. Thank you!
